name: SAM Validate, Build, Test, Deploy
on:
  push:
    branches: [ main ]

jobs:
  sam-validate-build-test-deploy:
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies with Apt Get
        run: |
          sudo apt-get update
          sudo apt-get install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update
          sudo apt-get install python3.8 jq -y
      - name: Install Pip Dependencies for CI
        run: |
          pip3 install pytest
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: SAM Validate
        run: |
          sam validate
      - name: SAM Build
        run: |
          sam build --use-container
      - name: Run unit tests
        run: |
          cd hello-world/
          npm install
        #  npm test
      - name: SAM Deploy
        run: |
          sam deploy --template-file .aws-sam/build/template.yaml \
            --stack-name product \
            --s3-bucket samartifactbuckettm \
            --parameter-overrides \
              'ParameterKey=Name,ParameterValue=example' \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset

      #  - name: Run unit tests
            #    run: |
           #       python3 -m pytest -s -vvv ./tests/unit/ siehe: https://github.com/aws-samples/aws-sam-github-actions-example/tree/main